# Generated by the VDI Image Factory Image Builder. This file contains no secrets.
# Supply the temporary WinRM password separately, for example through
# the PKR_VAR_winrm_password environment variable.
image_name           = "vdi-win11-engineering"
image_version        = "2026.09.1"
windows_image_index  = 6
cpus                 = 4
memory_mb            = 8192
disk_size_mb         = 81920
switch_name          = "Default Switch"
ui_language          = "en-US"
locale               = "en-US"
time_zone            = "UTC"
application_profiles = ["developer"]
include_applications = []
exclude_applications = ["Postman.Postman"]
run_optimizer        = false
optimizer_template   = "AutoSelect"
