#Requires -Version 5.1
# MCS machine catalog plan generated by the VDI Image Factory Image Builder.
# Nothing in this script has been executed. Review every value, load the
# Citrix PowerShell SDK, and run it first against a non-production site.
# Machines: VDI-ENG-001 to VDI-ENG-025 (25) in OU=Engineering,OU=VDI,DC=corp,DC=example,DC=test
$ErrorActionPreference = 'Stop'

# Snapshot of the imported master VM; adjust it to the snapshot you created.
$masterImageVM = 'XDHyp:\HostingUnits\Primary\vdi-win11-engineering.vm\vdi-win11-engineering-2026.09.1.snapshot'

function Wait-ProvTask {
    param([Parameter(Mandatory)][guid]$TaskId)
    $task = Get-ProvTask -TaskId $TaskId
    while ($task.Active) {
        Start-Sleep -Seconds 30
        $task = Get-ProvTask -TaskId $TaskId
    }
    if ($task.TaskState -ne 'Finished') {
        throw "Provisioning task $TaskId ended in state $($task.TaskState)."
    }
}

# 1. Identity pool: machine names, domain, and OU for the new computer accounts.
New-AcctIdentityPool -IdentityPoolName 'Engineering Desktops' `
    -NamingScheme 'VDI-ENG-###' -NamingSchemeType Numeric `
    -Domain 'corp.example.test' -OU 'OU=Engineering,OU=VDI,DC=corp,DC=example,DC=test' | Out-Null

# 2. Provisioning scheme based on the golden image snapshot.
$schemeTask = New-ProvScheme -ProvisioningSchemeName 'Engineering-W11' `
    -HostingUnitName 'Primary' -IdentityPoolName 'Engineering Desktops' `
    -MasterImageVM $masterImageVM -VMCpuCount 2 -VMMemoryMB 8192 `
    -CleanOnBoot -RunAsynchronously
Wait-ProvTask -TaskId $schemeTask
$provScheme = Get-ProvScheme -ProvisioningSchemeName 'Engineering-W11'

# 3. Broker machine catalog.
$catalog = New-BrokerCatalog -Name 'Engineering Desktops' `
    -AllocationType Random -ProvisioningType MCS -SessionSupport SingleSession `
    -PersistUserChanges Discard -MachinesArePhysical $false `
    -ProvisioningSchemeId $provScheme.ProvisioningSchemeUid

# 4. Computer accounts and virtual machines.
$accounts = New-AcctADAccount -IdentityPoolName 'Engineering Desktops' -Count 25
$vmTask = New-ProvVM -ProvisioningSchemeName 'Engineering-W11' `
    -ADAccountName @($accounts.SuccessfulAccounts.ADAccountName) -RunAsynchronously
Wait-ProvTask -TaskId $vmTask

# 5. Register the new machines with the catalog.
$hostingUnit = Get-Item -LiteralPath 'XDHyp:\HostingUnits\Primary'
$connection = Get-BrokerHypervisorConnection `
    -HypHypervisorConnectionUid $hostingUnit.HypervisorConnection.HypervisorConnectionUid
foreach ($vm in Get-ProvVM -ProvisioningSchemeName 'Engineering-W11') {
    Lock-ProvVM -ProvisioningSchemeName 'Engineering-W11' -Tag 'Brokered' -VMID @($vm.VMId)
    New-BrokerMachine -CatalogUid $catalog.Uid -MachineName $vm.ADAccountSid `
        -HostedMachineId $vm.VMId -HypervisorConnectionUid $connection.Uid | Out-Null
}
